### ISSUE TITLE
Update the pencil icon language

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/introduction-to-github#26]
As is brought up in [the community forum](https://github.community/t5/GitHub-Learning-Lab/Where-s-the-pencil-icon/m-p/26081#M854), next time we audit this course, we should change the instructions away from "pencil icon" and into something more generic so that it applies to versions of GitHub with the pencil icon and with the `...` hamburger menu.

**Comment by brianamarie** [comment]
@lmkeston, this came up from another user. I saw that you were looking for Learning Lab maintenance items. This may be one that is approachable. It would start with finding the response files that mention the "pencil icon". Maybe this could be solved by removing the language describing the button altogether, and adding a note at the bottom of the instructions like:

```
> Note: Can't find the button to edit the file? It may look like a pencil, or it may look like three dots.
```

**Comment by lmkeston** [comment]
@brianamarie : i accidentally pushed this directly to master, but all i changed was the markdown on two files. do you want to take a quick look and if it's ok, close this issue?  thanks - sorry about that

**Comment by brianamarie** [comment]
@lmkeston the commit and changes look good! Thank you for making the updates.

I wonder if we should consider protected branches for these course repos to avoid accidental pushes to master 🤔 I'll open an issue in our private `learning-lab-content` repo to discuss.

Anyway, thank you! 🎉
