### ISSUE TITLE
Changes to the reveal.js dependency

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/introduction-to-github#42]
The [template repo](https://github.com/githubtraining/caption-this-template) relies on [reveal.js](https://github.com/hakimel/reveal.js). At the time we created this course, the only way to utilize reveal.js was through a submodule. 

As of earlier today, the submodule was checked out to a [2017 commit](https://github.com/hakimel/reveal.js/tree/a349ff43c58c23f9c837b8ea9b5fc7d4761b8de3), so I did I tried to make this a little easier today.

Today, here are the changes implemented:
- We now consume reveal.js via its [Node module](https://www.npmjs.com/package/reveal.js)
- We no longer use the reveal.js [submodule](https://github.com/githubtraining/caption-this-template/commit/749192b3e6e2af4a49c1231e065e420f77e50b3d)
- Because we rely on GitHub Pages for static hosting, we [reference files](https://github.com/githubtraining/caption-this-template/commit/78e8155e1514e475fdc03a71d7e6a6ad38f39306) in the `node_modules` folder directly

I'll close this out in a couple of days but thought it was worth explaining for folks that might come in behind me trying to make changes to this course.

**Comment by lmkeston** [comment]
Seems to be working properly!
