### ISSUE TITLE
GitHub Slideshow pages site does not have control arrows #73

### ISSUE THREAD

**Issue by ernest-phillips** [githubtraining/introduction-to-github#58]
**Describe the bug**

Users from the [community forum](https://github.community/t/github-slideshow-not-working/134378) have reported this experience. 
After deploying Pages site, there are no controls for progressing through the slideshow.

![Screen Shot 2020-10-26 at 11 38 39 AM](https://user-images.githubusercontent.com/5134583/97214116-d2cf0480-177f-11eb-8735-491c1db36f80.png)

Link to my Page https://ernest-phillips.github.io/github-slideshow/#/ 

Based on the developer tools, I expect to see a right arrow control on the bottom right of the screen.
Changing zoom does not help button to appear.

**To Reproduce**
1. Start the [Introduction to GitHub](https://lab.github.com/githubtraining/introduction-to-github) course 
2. Complete steps 1-3 
3. Go to your deployed GitHub Pages site
4. Try to click through the slideshow

This was tested in:
Google Chrome browser 86.0.4240.111 (mobile also)
Firefox 81.0.2 
Safari 14.0

**Comment by jedpepper** [comment]
We all have it working now 👍

**Comment by Calorion** [comment]
It is not working for me. I kept tapping the right arrow on my keyboard with no effect, and there is no visible arrow on the screen. https://calorion.github.io/github-slideshow/
<img width="1012" alt="Screen Shot 2021-02-26 at 11 57 16 AM" src="https://user-images.githubusercontent.com/3050950/109337018-ccce5a80-7829-11eb-8135-bf1cbf12e551.png">

**Comment by ernest-phillips** [comment]
> It is not working for me. I kept tapping the right arrow on my keyboard with no effect, and there is no visible arrow on the screen. https://calorion.github.io/github-slideshow/
> <img alt="Screen Shot 2021-02-26 at 11 57 16 AM" width="1012" src="https://user-images.githubusercontent.com/3050950/109337018-ccce5a80-7829-11eb-8135-bf1cbf12e551.png">

Make sure to create a new markdown file in the `_posts` folder. There should be a new issue in your repository that explains what to do. Right now you only have one post and that is the represents the initial slide in the deck. So, the arrow will not show. Once the new post is created, you should be able to load your Pages site with the new slide.

**Comment by Calorion** [comment]
Okay, sure, but for people just doing this, they don’t know that the reason that they don’t see an arrow is that they are going to be told to create another slide in the future. So something to that effect in the instructions would be good, just to reduce confusion.
